insert into products (product_name, brand, price, in_stock) values ('Lenovo S800', 'Lenovo', 24.99, 't');
insert into products (product_name, brand, price, in_stock) values ('HTC One X', 'HTC', 39.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung R260 Chrono', 'Samsung', 3.29, 't');
insert into products (product_name, brand, price, in_stock) values ('Yezz Andy YZ1100', 'Yezz', 2.29, 't');
insert into products (product_name, brand, price, in_stock) values ('Spice Mi-500 Stellar Horizon', 'Spice', 15.99, 't');
insert into products (product_name, brand, price, in_stock) values ('LeEco Le 2', 'LeEco', 44.99, 't');
insert into products (product_name, brand, price, in_stock) values ('OnePlus 6T McLaren', 'OnePlus', 5.49, 't');
insert into products (product_name, brand, price, in_stock) values ('LG X Skin', 'LG', 4.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung Metro 360', 'Samsung', 15.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Lenovo A789', 'LG', 0.99, 't');
insert into products (product_name, brand, price, in_stock) values ('LG X4+', 'LG', 2.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Huawei Y7 (2019)', 'Huawei', 35, 't');
insert into products (product_name, brand, price, in_stock) values ('BLU G70', 'BLU', 199, 't');
insert into products (product_name, brand, price, in_stock) values ('Nokia 3230', 'Nokia', 6.49, 't');
insert into products (product_name, brand, price, in_stock) values ('vivo Y30', 'vivo', 18.99, 't');
insert into products (product_name, brand, price, in_stock) values ('BLU Disco2GO II', 'BLU', 5.49, 't');
insert into products (product_name, brand, price, in_stock) values ('ZTE Blade G', 'ZTE', 4.49, 't');
insert into products (product_name, brand, price, in_stock) values ('alcatel One Touch Pixi', 'alcatel', 12.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Sagem my100X', 'Sagem', 15.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Gionee Elife S7', 'Gionee', 22.99, 't');
insert into products (product_name, brand, price, in_stock) values ('vivo Z3i', 'vivo', 39.99, 'f');
insert into products (product_name, brand, price, in_stock) values ('Micromax A63 Canvas Fun', 'Micromax', 4.29, 't');
insert into products (product_name, brand, price, in_stock) values ('Motorola C115', 'Motorola', 22.99, 'f');
insert into products (product_name, brand, price, in_stock) values ('alcatel One Touch Tab 7', 'alcatel', 39.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung Galaxy A42 5G', 'Samsung', 3.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Gionee Ctrl V5', 'Gionee', 12.99, 't');
insert into products (product_name, brand, price, in_stock) values ('BlackBerry Curve 8330', 'BlackBerry', 1.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Nokia 6800', 'Nokia', 29.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung Galaxy Express Prime', 'Samsung', 2.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Vodafone 228', 'Vodafone', 64.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung Propel Pro', 'Samsung', 3.49, 't');
insert into products (product_name, brand, price, in_stock) values ('vivo Y52s', 'vivo', 24.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Philips Fisio 610', 'Philips', 49.99, 'f');
insert into products (product_name, brand, price, in_stock) values ('Wiko Lenny2', 'Wiko', 1.29, 'f');
insert into products (product_name, brand, price, in_stock) values ('Samsung T369', 'Samsung', 3.49, 't');
insert into products (product_name, brand, price, in_stock) values ('Honor 20 lite', 'Honor', 3.99, 't');
insert into products (product_name, brand, price, in_stock) values ('BLU Dash L3', 'BLU', 2.79, 't');
insert into products (product_name, brand, price, in_stock) values ('Gionee S6 Pro', 'Gionee', 2.69, 't');
insert into products (product_name, brand, price, in_stock) values ('Celkon C337', 'Celkon', 4.49, 't');
insert into products (product_name, brand, price, in_stock) values ('alcatel OT-E225', 'alcatel', 19.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Ericsson GF 788e', 'Ericsson', 6.99, 't');
insert into products (product_name, brand, price, in_stock) values ('LG G3', 'LG', 7.49, 't');
insert into products (product_name, brand, price, in_stock) values ('Unnecto Drone Z', 'Unnecto', 149.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Philips W8510', 'Philips', 8.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Celkon A35k Remote', 'Celkon', 24.99, 't');
insert into products (product_name, brand, price, in_stock) values ('verykool i130', 'verykool', 1.89, 't');
insert into products (product_name, brand, price, in_stock) values ('Motorola V535', 'Motorola', 14.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Sagem my302X', 'Sagem', 39.99, 't');
insert into products (product_name, brand, price, in_stock) values ('HTC S710', 'HTC', 29.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung P730', 'Samsung', 3.99, 'f');
insert into products (product_name, brand, price, in_stock) values ('Huawei G7002', 'Huawei', 2.79, 't');
insert into products (product_name, brand, price, in_stock) values ('alcatel Fire 7', 'alcatel', 5.49, 'f');
insert into products (product_name, brand, price, in_stock) values ('Motorola M3788', 'Motorola', 3.79, 'f');
insert into products (product_name, brand, price, in_stock) values ('Motorola PEBL U6', 'Motorola', 32.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Nokia Lumia 730 Dual SIM', 'Nokia', 24.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Realme C1', 'Realme', 2.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Nokia 8910i', 'Nokia', 24.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Sagem MW 3026', 'Sagem', 29.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Motorola SLVR L7', 'Motorola', 19.99, 't');
insert into products (product_name, brand, price, in_stock) values ('i-mobile Hitz 210', 'i-mobile', 29.99, 't');
insert into products (product_name, brand, price, in_stock) values ('ZTE Grand X LTE T82', 'ZTE', 3.99, 't');
insert into products (product_name, brand, price, in_stock) values ('iNQ iNQ1', 'iNQ', 54.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung E2230', 'Samsung', 2.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung N620', 'Samsung', 5.49, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung Galaxy Tab 4 7.0 3G', 'Samsung', 3.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Motorola One 5G UW', 'Motorola', 3.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Panasonic Eluga I7 (2019)', 'Panasonic', 59.99, 't');
insert into products (product_name, brand, price, in_stock) values ('T-Mobile REVVL 5G', 'T-Mobile', 39.99, 't');
insert into products (product_name, brand, price, in_stock) values ('LG KP235', 'LG', 14.99, 't');
insert into products (product_name, brand, price, in_stock) values ('HTC One (M8i)', 'HTC', 3.99, 'f');
insert into products (product_name, brand, price, in_stock) values ('Unnecto Drone Z', 'Unnecto', 8.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung Galaxy Ace Advance S6800', 'Samsung', 109.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Motorola M3188', 'Motorola', 99.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Maxwest Blade', 'Maxwest', 3.29, 't');
insert into products (product_name, brand, price, in_stock) values ('Archos 55 Graphite', 'Archos', 5.29, 't');
insert into products (product_name, brand, price, in_stock) values ('Asus Zenfone 3s Max ZC521TL', 'Asus', 99.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Apple iPad 3 Wi-Fi', 'Apple', 39.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Motorola Moto G 5G Plus', 'Motorola', 39.99, 'f');
insert into products (product_name, brand, price, in_stock) values ('Apple iPad 3 Wi-Fi + Cellular', 'Apple', 2.29, 't');
insert into products (product_name, brand, price, in_stock) values ('Oppo A73', 'Oppo', 4.29, 't');
insert into products (product_name, brand, price, in_stock) values ('verykool T7445', 'verykool', 30, 'f');
insert into products (product_name, brand, price, in_stock) values ('Samsung ZV10', 'Samsung', 19.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Wiko Sunny3 Plus', 'Wiko', 3.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Allview X4 Soul Lite', 'Allview', 8.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung I100 Gem', 'Samsung', 3.79, 'f');
insert into products (product_name, brand, price, in_stock) values ('HTC U Ultra', 'HTC', 24.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Sagem MC 950', 'Sagem', 29.99, 't');
insert into products (product_name, brand, price, in_stock) values ('ZTE Blade A2', 'ZTE', 29.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Sewon SG-2100CS', 'Sewon', 29.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Samsung Propel Pro', 'Samsung', 9.99, 't');
insert into products (product_name, brand, price, in_stock) values ('HTC Desire 326G dual sim', 'HTC', 69.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Panasonic VS7', 'Panasonic', 3.99, 't');
insert into products (product_name, brand, price, in_stock) values ('LG GX300', 'LG', 15.49, 't');
insert into products (product_name, brand, price, in_stock) values ('Sony Ericsson T290', 'Sony', 12.99, 't');
insert into products (product_name, brand, price, in_stock) values ('NIU Pana N105', 'NIU', 19.99, 'f');
insert into products (product_name, brand, price, in_stock) values ('QMobile Noir S5', 'QMobile', 6.99, 't');
insert into products (product_name, brand, price, in_stock) values ('ZTE Maven', 'ZTE', 2.49, 't');
insert into products (product_name, brand, price, in_stock) values ('Philips M200', 'Philips', 39.99, 't');
insert into products (product_name, brand, price, in_stock) values ('Micromax A90', 'Micromax', 14.99, 'f');
insert into products (product_name, brand, price, in_stock) values ('LG KS660', 'LG', 59.99, 't');